### ISSUE TITLE
The EventHandler table must support a locking process

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_networks#190]
The Periodic Service of EventHanlder get from the database the list of event that must be executed

If have some delays the next periodic service execution get the same list of event to trait and this cause a problem.

to solve that the database table must have a column with a lock status

the process is:

- the periodic service get a list of events to execute
- the periodic service update the lock status column to "lock"
- another periodic execution must read the list of event that are not in lock status

**Comment by vladyslav-fenchak** [comment]
The solution so that the same row is not processed X times simultaneously is to add the following to the query that fetches the records from the queue:
```sql
SELECT *
FROM %s
WHERE retry <= %d
ORDER BY creation_date
LIMIT %d
FOR UPDATE
SKIP LOCKED;
```

**Comment by andrea-mucci** [comment]
@vladyslav-fenchak are you sure that the `FOR UPDATE` is the right key?
the `FOR UPDATE` create a lock for `UPDATE` process and we need to lock the select as well
for that the best solution seem to be `FOR SHARE`

**Comment by vladyslav-fenchak** [comment]
@andrea-mucci and @garciparedes  on further investigation, I propose the following solution for the 2 outstanding points:

1. For our case, which is a processing queue, we would use FOR UPDATE:
```python
FOR UPDATE is equivalent to an exclusive lock on the row selected, meaning that no other backend can take a 
FOR UPDATE lock on the same row and waits until the other other transaction finishes. FOR SHARE means that all 
the other backends can take a FOR SHARE lock on those rows. No FOR UPDATE locks can be taken on rows already 
locked with FOR SHARE. It is also possible to use the NOWAIT option, making the server return an error if 
there is a wait situation.
```

2. As the code currently stands, transactions are automatic. Whenever you do an "await self.submit_query", aiopg underneath creates and commits the transaction.

In the actual code you can see that a total of 3 queries are executed, so 3 transactions are also created:
```python
        iterable = self.submit_query_and_iter(
            _SELECT_NON_PROCESSED_ROWS_QUERY % (self.TABLE_NAME, self._retry, self._records),
        )
        async for row in iterable:
            dispatched = False
            try:
                await self.dispatch_one(row)
                dispatched = True
            except Exception as exc:
                log.warning(exc)
            finally:
                if dispatched:
                    await self.submit_query(_DELETE_PROCESSED_QUERY % (self.TABLE_NAME, row[0]))
                else:
                    await self.submit_query(_UPDATE_NON_PROCESSED_QUERY % (self.TABLE_NAME, row[0]))
```

The proposal is to modify the code in the following way so that the transaction is handled manually, which aiopg allows and expressly says here on this cases: https://aiopg.readthedocs.io/en/stable/core.html#transactions :

```python
        pool = await self.pool
        with await pool.cursor() as cursor:
            # aiopg works in autocommit mode, meaning that you have to use transaction in manual mode.
            # Read more details: https://aiopg.readthedocs.io/en/stable/core.html#transactions.
            await cursor.execute("BEGIN")

            # Select records lock them FOR UPDATE
            await cursor.execute(_SELECT_NON_PROCESSED_ROWS_QUERY % (self.TABLE_NAME, self._retry, self._records),)
            result = await cursor.fetchall()

            for row in result:
                dispatched = False
                try:
                    await self.dispatch_one(row)
                    dispatched = True
                except Exception as exc:
                    log.warning(exc)
                finally:
                    if dispatched:
                        await cursor.execute(_DELETE_PROCESSED_QUERY % (self.TABLE_NAME, row[0]))
                    else:
                        await cursor.execute(_UPDATE_NON_PROCESSED_QUERY % (self.TABLE_NAME, row[0]))

            # Manually commit
            await cursor.execute("COMMIT")
```
