### ISSUE TITLE
Remove unsubscription if subscription failed

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_networks#249]
Currently, when a microservice starts it tries to subscribe to a `discovery` service already running.
Also, if the microservice crashes it tries to unsubscribe from the `discovery` service.

Thus, an inconsistency occurs when the microservice crashes due to a
```minos.networks.exceptions.MinosDiscoveryConnectorException: There was a problem while trying to subscribe.```
 The problem is it could not subscribe, but when it crashes it tries to unsubscribe causing a
```minos.networks.exceptions.MinosDiscoveryConnectorException: There was a problem while trying to unsubscribe.```

**Comment by garciparedes** [comment]
Hi @albamig! As that behaviour comes from `minos.common.MinosSetup` I'll proceed to close this issue because it will be resolved when https://github.com/Clariteia/minos_microservice_common/issues/446 is done!
