### ISSUE TITLE
EventModel: extract the name from ModelBase method "get_namespace"

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_networks#30]
The EventModel have an attribute called "name"

this attribute must be filled with the value returned by "get_namespace" of the Aggregate Instance

```python

aggregate_instance = UserAggregate()

event_instance = EventModel(name=aggregate_instance.classname()....)

```

**Comment by garciparedes** [comment]
This issue is closely related to https://github.com/Clariteia/minos_microservice_common/issues/92, which is already resolved 🤗
