### ISSUE TITLE
`@enroute` decorator does not fit `periodic` events

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_networks#402]
As we've discussed in #400 it's somewhat weird to have the `periodic` events grouped within `@enroute`.

We've come to agree that moving it to an independent decorator doesn't make any good either, so the one possibility remaining is to think of a new name for `@enroute`. Maybe something like binding ports and adapters might be good? :man_shrugging:

**Comment by garciparedes** [comment]
Closing this issue as it is moved to https://github.com/minos-framework/minos-python/issues/74
