### ISSUE TITLE
Automatic `Content-Type` parsing

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_networks#421]
Currently `Minos` just parses requests for `application/json` `Content-Type`.

It would be interesting if `Minos` would read the `Content-Type` of the request and process automatically the most common types, such as `Avro`, `form-encoded` and so.

For example:
For the media type `application/x-www-form-encoded`, the framework might do something like:
```python
import urllib.parse

req = request.raw_request
if req == 'application/x-www-form-encoded':
    json_content = await req.json(loads=urllib.parse.parse_qs)
```

**Comment by garciparedes** [comment]
Hi @albamig,

Yes! We should add this feature, as `json` is not the unique format for `HTTP` requests 😅
Together with the case you initially found on this issue, I'll add the support for `application/octet-stream` (for `byte-like` requests) with the following strategy: `await request.raw_request.read()`

Let me know what is the content type for `avro` requests and I will also add the support for automatic parsing this format 🙂

**Comment by albamig** [comment]
I'm sending Avro requests as `avro/binary`.

The following snippet works for decoding with `fastavro`, in case it saves you time :wink: 
```python
stream: StreamReader = request.raw_request.content
content = BytesIO(await stream.read())

for record in reader(content):
 logger.info(record)
```

Thanks a lot @garciparedes

**Comment by garciparedes** [comment]
In order to keep this issue as shorter as possible, I decided to create #463 to especifically add support for `multipart/*` content type.
