### ISSUE TITLE
EventHandler must store the event on database

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_networks#61]
The EventHandler must ensure that the events received are transactional, this is covered using a transactional database ( postgreSQL ) and queue for the events received.

The EventHandler, for every set of events that receive must:

- [x] check that the binary received ( msg.value ) is a well formatted eventModel, this can be do it loading the binary string into the EventModel instance.
```python
async for msg in consumer:
    # the handler receive a message and store in the queue database
    topic = msg.topic
    partition = msg.partition
    event_binary = msg.value
    # check if the event binary string is well formatted
    event_instance = Event.from_avro_bytes(event_binary)
```
- [x] if the event model validation is correct, the EventHandler must add the event into the queue table ( event_queue )
```text
Database fields:
1. ID
2. topic
3. partition
3. binary
4. creation_date
```

```python
"""
EXAMPLE CODE
"""
async def event_queue_add(self, topic: str, partition: int, binary: bytes):
    async with aiopg.connect(self._db_dsn) as connect:
        async with connect.cursor() as cur:
            await cur.execute(
                "INSERT INTO event_queue (topic, partition, binary, creation_date) VALUES (%s, %s, %s, %s) RETURNING id;",
                (topic, partition, binary, datetime.datetime.now(),),
            )

            queue_id = await cur.fetchone()
            affected_rows = cur.rowcount

    return affected_rows, queue_id[0]
```

**Comment by vladyslav-fenchak** [comment]
@garciparedes would the following way of converting the event from bytes to instances be correct?
```python
event_instance = Event.from_avro_bytes(event_binary=event_binary)
```

Thanks.

**Comment by garciparedes** [comment]
Hi @vladyslav-fenchak!

It's not exactly as you did it, but really similar (the name of the argument is `raw` instead of `event_binary`, but as it's the first one, it's not needed to be specified). In summary, the right way is as follows:

```python
from minos.common import Event


event_binary = ...
event = Event.from_avro_bytes(event_binary)
```
> @garciparedes would the following way of converting the event from bytes to instances be correct?
> 
> ```python
> event_instance = Event.from_avro_bytes(event_binary=event_binary)
> ```
> 
> Thanks.

**Comment by vladyslav-fenchak** [comment]
Done and uploaded. Close issue on merge.
