### ISSUE TITLE
Python code Profiling

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_networks#76]
Check the implementation and the use of [PyInstrument](https://github.com/joerick/pyinstrument/)

get the report in plain format and generate a flame graph

the flame graph ( svg format ) must be uploaded to:

1. repository branch
2. external website for future reviews

**Comment by garciparedes** [comment]
Closing this issue as it is moved to https://github.com/minos-framework/minos-python/issues/68
