### ISSUE TITLE
The `commands` and `events` queues shares the same table. Is it right?

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_networks#93]
The current implementation of the `minos.networks.MinosBroker` is the parent class both for `MinosEventBroker` and `MinosCommandBroker`. 

This makes sense because both brokers have similar logic. Also, this implies that both of theses clases will share a common table used as a queue if the `events` queue and the `commands` queue is allocated on the same Database, which is fine. The table name is `producer_queue`.

After the messages are enqueued on that table, another component (the `MinosQueueService`) periodically dequeues a certain amount of messages and publishes them into the `Kafka` broker (to be consumed by the handlers in another micro-services).

This issue was created because the current configuration allows to define the same (or different) databases for `events` and `broker` queues, but doesn't allow to configure multiple `MinosQueueDispatcher` configurations, so that we are currently restricted to use a single database (and then one table) for both queues in order to be compatible with the current config schema.

The trouble is that currently the `minos.networks.MinosQueueDispatcher` only allows to load the `events` database from config.

For this reason, I created this Issue until we find an intermediate solution that fits both cases.

**Comment by andrea-mucci** [comment]
@vladyslav-fenchak this is for the Handler, not for the Broker.
my mistake

**Comment by garciparedes** [comment]
I included a reference to the line in which the `minos.common.MinosConfig` is used by the `minos.networks.MinosQueueDispatcher`:
https://github.com/Clariteia/minos_microservice_networks/blob/433f158207bb8ce4e5c697a492eaf82d0ee2e7ad/minos/networks/broker/dispatchers.py#L43-L56

**Comment by garciparedes** [comment]
As you said, I'll proceed to close it because the question is resolved. Thanks!
